In [55]:
#API Banxico
# Dependencies
import requests
import json
import pandas as pd 
from pprint import pprint
banxico_key = "85c8edeab72128102cdad764f0a2d4532c336d22690a51104b500fb6f077ed4c"

In [47]:
url = "https://www.banxico.org.mx/SieAPIRest/service/v1/series/"

In [51]:
Series = "SF43788"
fecha_inicial = ["2018-8-2/2018-8-3", "2018-10-4/2018-10-5", "2018-11-15/2018-11-16", "2018-12-20/2018-12-21",
                 "2019-2-7/2019-2-8", "2019-3-28/2019-3-29", "2019-5-16/2019-5-17", "2019-6-27/2019-6-28", 
                 "2019-8-15/2019-8-16", "2019-9-26/2019-9-27", "2019-11-14/2019-11-15", "2019-12-19/2019-12-20"]
fxt = []
fxt_1 = []
for fecha in fecha_inicial:
    url_consulta = [f"{url}{Series}/datos/{fecha}?token={banxico_key}"]
    for query in url_consulta: 
        data=requests.get(query).json()
        fxt.append(data["bmx"]["series"][0]["datos"][0]["dato"])
        fxt_1.append(data["bmx"]["series"][0]["datos"][1]["dato"])

In [52]:
Series = "SF43878"
fecha_inicial = ["2018-8-2/2018-8-3", "2018-10-4/2018-10-5", "2018-11-15/2018-11-16", "2018-12-20/2018-12-21",
                 "2019-2-7/2019-2-8", "2019-3-28/2019-3-29", "2019-5-16/2019-5-17", "2019-6-27/2019-6-28", 
                 "2019-8-15/2019-8-16", "2019-9-26/2019-9-27", "2019-11-14/2019-11-15", "2019-12-19/2019-12-20"]
tiie91 = []
tiie91_1 = []
for fecha in fecha_inicial:
    url_consulta = [f"{url}{Series}/datos/{fecha}?token={banxico_key}"]
    for query in url_consulta: 
        data=requests.get(query).json()
        tiie91.append(data["bmx"]["series"][0]["datos"][0]["dato"])
        tiie91_1.append(data["bmx"]["series"][0]["datos"][1]["dato"])

In [65]:
Banxico_dict = {"Tipo de Cambio": fxt, "Tipo de Cambio (t+1)": fxt_1, "Tasa de Interés": tiie91, 
                "Tasa de Interés (t+1)": tiie91_1}
Banxico_data = pd.DataFrame(Banxico_dict)
Banxico_data["Dif Tipo de Cambio"] = 100*(Banxico_data["Tipo de Cambio"].astype(float) - Banxico_data["Tipo de Cambio (t+1)"].astype(float))
Banxico_data["Dif Tasa de Interés"] = 100*(Banxico_data["Tasa de Interés"].astype(float) - Banxico_data["Tasa de Interés (t+1)"].astype(float))
Banxico_data["Fecha"] = fecha_inicial
Banxico_data= Banxico_data[['Fecha', 'Tipo de Cambio', "Dif Tipo de Cambio", 'Tipo de Cambio (t+1)', "Tasa de Interés",
                           "Tasa de Interés (t+1)", "Dif Tasa de Interés"]]
Banxico_data

,Fecha,Tipo de Cambio,Dif Tipo de Cambio,Tipo de Cambio (t+1),Tasa de Interés,Tasa de Interés (t+1),Dif Tasa de Interés
0,2018-8-2/2018-8-3,18.6080,5.60,18.5520,8.1537,8.1550,-0.13
1,2018-10-4/2018-10-5,19.1650,27.25,18.8925,8.1600,8.1575,0.25
2,2018-11-15/2018-11-16,20.2110,12.15,20.0895,8.3228,8.3604,-3.76
3,2018-12-20/2018-12-21,19.9285,-1.35,19.9420,8.4750,8.4887,-1.37
4,2019-2-7/2019-2-8,19.1375,8.00,19.0575,8.5967,8.5950,0.17
5,2019-3-28/2019-3-29,19.3440,-6.20,19.4060,8.5040,8.4975,0.65
6,2019-5-16/2019-5-17,19.0565,-9.30,19.1495,8.5146,8.5150,-0.04
7,2019-6-27/2019-6-28,19.1430,-4.80,19.1910,8.4900,8.4833,0.67
8,2019-8-15/2019-8-16,19.6655,6.85,19.5970,8.3750,8.3350,4.00
9,2019-9-26/2019-9-27,19.6185,-10.05,19.7190,8.0150,8.0025,1.25
10,2019-11-14/2019-11-15,19.3760,16.73,19.2087,7.7287,7.6893,3.94
11,2019-12-19/2019-12-20,18.9480,2.40,18.9240,7.5575,7.5482,0.93